// Auto generated file, do not edit this file

import dotenv from "dotenv";
dotenv.config();

import {
  IERC20ModuleConfig,
  IEtherscanModuleConfig,
  ISwapModuleConfig,
  ITradeModuleConfig,
} from "@deepchain-labs/nest-modules-config";

import { AlpacaModule } from "@deepchain-labs/nest-alpaca-module";
import { CacheModule } from "@deepchain-labs/nest-cache-module";
import { CoingeckoModule } from "@deepchain-labs/nest-coingecko-module";
import { EtherscanModule } from "@deepchain-labs/nest-etherscan-module";
import { SwapModule } from "@deepchain-labs/nest-swap-module";
import { Module } from "@nestjs/common";

const networkConfig: IERC20ModuleConfig["networkConfig"] &
  ISwapModuleConfig["networkConfig"] &
  IEtherscanModuleConfig["networkConfig"] &
  ITradeModuleConfig["networkConfig"] = {
  5: {
    nativeTokenDecimals: 18,
    nativeTokenName: "GoerliETH",
    nativeTokenSymbol: "gETH",
    rpcUrl: process.env.GOERLI_RPC_URL || "",
    explorerBaseUrl: "https://api-goerli.etherscan.io/api",
    explorerApiKey: process.env.ETHERSCAN_API_KEY || "",
    swapRouterContractAddress: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
    quoterContractAddress: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6",
    nonfungiblePositionManagerContractAddress:
      "0xC36442b4a4522E871399CD717aBDD847Ab11FE88",
    uniswapV3FactoryContractAddress:
      "0x1F98431c8aD98523631AE4a59f267346ea31F984",
    alpacaEnv: "PAPER",
    signerPrivateKey: "",
    tradeContractAddress: "",
    commissionPercentage: 10,
    ignoreMarketClosed: true,
  },
  137: {
    nativeTokenDecimals: 18,
    nativeTokenName: "MATIC",
    nativeTokenSymbol: "MATIC",
    rpcUrl: process.env.POLYGON_RPC_URL || "abc",
    explorerBaseUrl: "https://api.polygonscan.com/api",
    explorerApiKey: process.env.POLYGONSCAN_API_KEY || "",
    swapRouterContractAddress: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
    quoterContractAddress: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6",
    nonfungiblePositionManagerContractAddress:
      "0xC36442b4a4522E871399CD717aBDD847Ab11FE88",
    uniswapV3FactoryContractAddress:
      "0x1F98431c8aD98523631AE4a59f267346ea31F984",
    alpacaEnv: "PAPER",
    signerPrivateKey: "",
    tradeContractAddress: "",
    commissionPercentage: 10,
    ignoreMarketClosed: true,
  },
};

@Module({
  imports: [
    // StartImport

    // ERC20Module.register({
    //   exposeController: true,
    //   networkConfig,
    //   REDIS_URL: "redis://localhost:6379",
    //   // global: true,
    // }),
    SwapModule.register({
      exposeController: true,
      networkConfig,
      global: true,
      // REDIS_URL: "redis://localhost:6379",
    }),
    AlpacaModule.register({
      exposeController: true,
      apiKeys: {},
      global: true,
    }),
    EtherscanModule.register({
      exposeController: true,
      networkConfig,
      global: true,
      // REDIS_URL: "redis://localhost:6370",
    }),
    CacheModule.register({
      REDIS_URL: "redis://localhost:6379",
      global: true,
    }),
    CoingeckoModule.register({ exposeController: true, global: true }),

    // EndImport
  ],
})
export class CodegenModule {}
